import { Component, input } from '@angular/core';
import { IonIcon } from '@ionic/angular';
import {
  arrowBackOutline,
  arrowForwardOutline,
  bookOutline,
  bulbOutline,
  calculatorOutline,
  calendarOutline,
  checkmarkCircleOutline,
  chevronForwardOutline,
  clipboardOutline,
  closeCircleOutline,
  colorPaletteOutline,
  documentTextOutline,
  flaskOutline,
  fingerPrintOutline,
  globeOutline,
  languageOutline,
  keyOutline,
  mailOutline,
  informationCircleOutline,
  hourglassOutline,
  warningOutline,
  peopleOutline,
  notificationsOutline,
  shieldCheckmarkOutline,
  logOutOutline,
  trashOutline,
  listOutline,
  playOutline,
  readerOutline,
  schoolOutline,
  settingsOutline,
  sparklesOutline,
  statsChartOutline,
  timerOutline,
  trophyOutline,
} from 'ionicons/icons';

const icons = {
  back: arrowBackOutline,
  forward: arrowForwardOutline,
  book: bookOutline,
  bulb: bulbOutline,
  mathematics: calculatorOutline,
  calendar: calendarOutline,
  correct: checkmarkCircleOutline,
  chevron: chevronForwardOutline,
  exam: clipboardOutline,
  wrong: closeCircleOutline,
  appearance: colorPaletteOutline,
  note: documentTextOutline,
  science: flaskOutline,
  fingerprint: fingerPrintOutline,
  'social-studies': globeOutline,
  english: languageOutline,
  language: languageOutline,
  key: keyOutline,
  mail: mailOutline,
  info: informationCircleOutline,
  time: hourglassOutline,
  warning: warningOutline,
  people: peopleOutline,
  notifications: notificationsOutline,
  shield: shieldCheckmarkOutline,
  logout: logOutOutline,
  trash: trashOutline,
  close: closeCircleOutline,
  list: listOutline,
  play: playOutline,
  reader: readerOutline,
  grade: schoolOutline,
  settings: settingsOutline,
  intelligence: sparklesOutline,
  progress: statsChartOutline,
  quiz: timerOutline,
  trophy: trophyOutline,
  syllabus: bookOutline,
};
@Component({
  selector: 'app-icon',
  imports: [IonIcon],
  host: { 'aria-hidden': 'true' },
  template: '<ion-icon [icon]="icons[name()]" aria-hidden="true" />',
  styles:
    ':host { display: inline-flex; flex: 0 0 auto; align-items: center; font-size: 1.3em; vertical-align: middle; } ion-icon { display: block; }',
})
export class IconComponent {
  readonly name = input.required<keyof typeof icons>();
  readonly icons = icons;
}
